### ISSUE TITLE
Update the version and publish

### ISSUE THREAD

**Issue by kishankanugula** [mpayetta/statsd-newrelic-backend#5]
It looks like still npm package pointing to older code. I don't see the latest code for example i don't see 'counter_rates' when i do "npm install statsd-newrelic-backend". If everything is fine, please update the version number in package.json and publish it to npm. Thank you.

**Comment by tvalasek** [comment]
"msg":"Error to be sent to collector:","component":"error_tracer","error":[0,"WebTransaction/Uri/*","transformMetric.customEvent[metricType] is not a function","TypeError",{"request_uri":"","userAttributes":{},"agentAttributes":{},"intrinsics":{},"stack_trace":["TypeError: transformMetric.customEvent[metricType] is not a function","    at Object.dispatch [as customEvent] (/node_modules/statsd-newrelic-backend/lib/dispatcher/dispatchers/custom-event.js:10:70)","    at dispatchMetric (/node_modules/statsd-newrelic-backend/lib/index.js:54:43)","    at Array.forEach (native)","    at /node_modules/statsd-newrelic-backend/lib/index.js:60:37","    at Array.forEach (native)","    at EventEmitter.onFlush (/node_modules/statsd-newrelic-backend/lib/index.js:49:29)","    at emitTwo (events.js:111:20)","    at EventEmitter.emit (events.js:191:7)","    at emitFlush (/statsd/stats.js:152:19)","    at Object.process_metrics (/statsd/lib/process_metrics.js:144:5)"]}]}
/node_modules/statsd-newrelic-backend/lib/dispatcher/dispatchers/custom-event.js:10
                metricValue = transformMetric.customEvent[metricType](statsdValue);
                                                                     ^

TypeError: transformMetric.customEvent[metricType] is not a function
    at Object.dispatch [as customEvent] (/node_modules/statsd-newrelic-backend/lib/dispatcher/dispatchers/custom-event.js:10:70)
    at dispatchMetric (/node_modules/statsd-newrelic-backend/lib/index.js:54:43)
    at Array.forEach (native)
    at /node_modules/statsd-newrelic-backend/lib/index.js:60:37
    at Array.forEach (native)
    at EventEmitter.onFlush (/node_modules/statsd-newrelic-backend/lib/index.js:49:29)
    at emitTwo (events.js:111:20)
    at EventEmitter.emit (events.js:191:7)
    at emitFlush (/statsd/stats.js:152:19)
    at Object.process_metrics (/statsd/lib/process_metrics.js:144:5)

**Comment by mpayetta** [comment]
Hi, I'm not sure what you mean with update package version and publish. No changes have been done to the package in months.
I'm not having enough free time lately, so feel free to submit PRs for bugfixes.
Thanks!
